biblio_user:
    resource: "@BiblioUserBundle/Resources/config/routing.yml"
    prefix:   /

biblio_general:
    resource: "@BiblioGeneralBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"