biblio_general_homepage:
    path:     /
    defaults: { _controller: BiblioGeneralBundle:Default:index }

biblio_general_adduser:
    path:     /adduser
    defaults: { _controller: BiblioGeneralBundle:Default:adduser }
biblio_general_edituser:
    path:     /edituser/{id}
    defaults: { _controller: BiblioGeneralBundle:Default:edituser }
biblio_general_deleteuser:
    path:     /deleteuser/{id}
    defaults: { _controller: BiblioGeneralBundle:Default:deleteuser }
biblio_general_showusers:
    path:     /showusers
    defaults: { _controller: BiblioGeneralBundle:Default:showusers }
biblio_general_showuser:
    path:     /showuser/{id}
    defaults: { _controller: BiblioGeneralBundle:Default:showuser }

biblio_general_addautor:
    path:     /addautor
    defaults: { _controller: BiblioGeneralBundle:Default:addautor }
biblio_general_editautor:
    path:     /editautor/{id}
    defaults: { _controller: BiblioGeneralBundle:Default:editautor }
biblio_general_deleteautor:
    path:     /deleteautor/{id}
    defaults: { _controller: BiblioGeneralBundle:Default:deleteautor }
biblio_general_showautors:
    path:     /showautors
    defaults: { _controller: BiblioGeneralBundle:Default:showautors }
biblio_general_showautor:
    path:     /showautor/{id}
    defaults: { _controller: BiblioGeneralBundle:Default:showautor }

biblio_general_showtypeslivre:
    path:     /showtypeslivre
    defaults: { _controller: BiblioGeneralBundle:Default:showtypeslivre }
biblio_general_showtypelivre:
    path:     /showtypelivre/{id}
    defaults: { _controller: BiblioGeneralBundle:Default:showtypelivre }


biblio_general_addlivre:
    path:     /addlivre
    defaults: { _controller: BiblioGeneralBundle:Default:addlivre }
biblio_general_editlivre:
    path:     /editlivre/{id}
    defaults: { _controller: BiblioGeneralBundle:Default:editlivre }
biblio_general_deletelivre:
    path:     /deletelivre/{id}
    defaults: { _controller: BiblioGeneralBundle:Default:deletelivre }
biblio_general_showlivres:
    path:     /showlivres
    defaults: { _controller: BiblioGeneralBundle:Default:showlivres }
biblio_general_showlivre:
    path:     /showlivre/{id}
    defaults: { _controller: BiblioGeneralBundle:Default:showlivre }

biblio_general_addexemplaire:
    path:     /addexemplaire
    defaults: { _controller: BiblioGeneralBundle:Default:addexemplaire }
biblio_general_editexemplaire:
    path:     /editexemplaire/{id}
    defaults: { _controller: BiblioGeneralBundle:Default:editexemplaire }
biblio_general_deleteexemplaire:
    path:     /deleteexemplaire/{id}
    defaults: { _controller: BiblioGeneralBundle:Default:deleteexemplaire }

biblio_general_addedition:
    path:     /addedition
    defaults: { _controller: BiblioGeneralBundle:Default:addedition }
biblio_general_editedition:
    path:     /editedition/{id}
    defaults: { _controller: BiblioGeneralBundle:Default:editedition }
biblio_general_deleteedition:
    path:     /deleteedition/{id}
    defaults: { _controller: BiblioGeneralBundle:Default:deleteedition }
biblio_general_showeditions:
    path:     /showeditions
    defaults: { _controller: BiblioGeneralBundle:Default:showeditions }
biblio_general_showedition:
    path:     /showedition/{id}
    defaults: { _controller: BiblioGeneralBundle:Default:showedition }

biblio_general_addemprunt:
    path:     /addemprunt/{idUser}/{idExemplaire}
    defaults: { _controller: BiblioGeneralBundle:Default:addemprunt }
biblio_general_editemprunt:
    path:     /editemprunt/{id}
    defaults: { _controller: BiblioGeneralBundle:Default:editemprunt }
biblio_general_deleteemprunt:
    path:     /deleteemprunt/{id}
    defaults: { _controller: BiblioGeneralBundle:Default:deleteemprunt }
biblio_general_showemprunts:
    path:     /showemprunts
    defaults: { _controller: BiblioGeneralBundle:Default:showemprunts }

biblio_general_openinghours:
    path:     /openinghours
    defaults: { _controller: BiblioGeneralBundle:Default:openinghours }

biblio_general_regulation:
    path:     /regulation
    defaults: { _controller: BiblioGeneralBundle:Default:regulation }

biblio_general_functioning:
    path:     /functioning
    defaults: { _controller: BiblioGeneralBundle:Default:functioning }

biblio_general_contact:
    path:     /contact
    defaults: { _controller: BiblioGeneralBundle:Default:contact }

biblio_general_townhall:
    path:     /townhall
    defaults: { _controller: BiblioGeneralBundle:Default:townhall }

biblio_general_addnews:
    path:    /addnews
    defaults: { _controller: BiblioGeneralBundle:Default:addnews }

biblio_general_messagecontact:
    path:    /messagecontact
    defaults: { _controller: BiblioGeneralBundle:Default:messagecontact }

biblio_general_showmessagecontact:
    path:    /showmessagecontact/{id}
    defaults: { _controller: BiblioGeneralBundle:Default:showmessagecontact }

biblio_general_deletemessagecontact:
    path:   /deletemessagecontact/{id}
    defaults: {_controller: BiblioGeneralBundle:Default:deletemessagecontact}