<?php

namespace Biblio\GeneralBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InscritRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscritRepository extends EntityRepository
{
}